version: '3.8'

services:
  frontend-prod:
    container_name: frontend-prod
    build: .
    environment:
      BUILD_TYPE: 'production'
    ports:
      - "3000:3000"
    networks:
      - frontend-network

  frontend-staging:
    container_name: frontend-test
    build: .
    environment:
      BUILD_TYPE: 'staging'
    ports:
      - "3001:3000"
    networks:
      - frontend-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend-prod
      - frontend-staging
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
