services:
  frontend-prod:
    container_name: frontend-prod
    build: .
    environment:
      BUILD_TYPE: 'production'
    ports:
      - "3000:3000"

  frontend-staging:
    container_name: frontend-test
    build: .
    environment:
      BUILD_TYPE: 'staging'
    ports:
      - "3001:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
